services:
  - type: web
    name: diabetalens-backend
    runtime: python
    region: oregon
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: ./models/hybrid_dl.h5
      - key: SCALER_PATH
        value: ./models/scaler.pkl
